# Generated by Django 5.2.4 on 2025-08-12 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permission_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameIndex(
            model_name='userpermission',
            new_name='user_permis_user_id_637b6a_idx',
            old_name='user_permissions_user_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='userpermission',
            new_name='user_permis_client__362bdb_idx',
            old_name='user_permissions_client_idx',
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
