# Generated by Django 5.2.4 on 2025-08-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['endpoint_category', 'name'], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='permissionscope',
            options={'ordering': ['hierarchy_level'], 'verbose_name': 'Permission Scope', 'verbose_name_plural': 'Permission Scopes'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name': 'User Permission', 'verbose_name_plural': 'User Permissions'},
        ),
    ]
