# Generated by Django 5.2.4 on 2025-08-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.IntegerField(blank=True, null=True)),
                ('quota_used', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
