# Generated by Django 5.2.4 on 2025-08-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_type', models.CharField(choices=[('amazon', 'Amazon'), ('mercadolibre', 'Mercado Libre'), ('shopify', 'Shopify'), ('ebay', 'eBay'), ('walmart', 'Walmart')], max_length=50)),
                ('feedback_type', models.CharField(choices=[('review', 'Review'), ('question', 'Pregunta'), ('comment', 'Comentario')], max_length=50)),
                ('marketplace_feedback_id', models.CharField(blank=True, max_length=100, null=True)),
                ('marketplace_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('feedback_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('answered', 'Respondido')], default='pending', max_length=50)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('verified_purchase', models.BooleanField(default=False)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedback', to='clients.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'db_table': 'customer_feedback',
            },
        ),
    ]
