# Generated by Django 5.2.4 on 2025-08-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subscription_plan', models.CharField(choices=[('basic', 'Básico'), ('premium', 'Premium'), ('enterprise', 'Empresarial')], default='basic', max_length=50)),
                ('api_quota', models.IntegerField(default=10000)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientMarketplaceCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_type', models.CharField(choices=[('amazon', 'Amazon'), ('mercadolibre', 'Mercado Libre'), ('shopify', 'Shopify'), ('ebay', 'eBay'), ('walmart', 'Walmart')], max_length=50)),
                ('marketplace_name', models.CharField(blank=True, max_length=100, null=True)),
                ('credentials', models.JSONField()),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('connection_status', models.CharField(choices=[('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('error', 'Error')], default='disconnected', max_length=50)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_credentials', to='clients.client')),
            ],
            options={
                'db_table': 'client_marketplace_credentials',
            },
        ),
    ]
