# Generated by Django 5.2.4 on 2025-08-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmarketplacecredentials',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='clientmarketplacecredentials',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientmarketplacecredentials',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si esta credencial está activa'),
        ),
        migrations.AddField(
            model_name='clientmarketplacecredentials',
            name='name',
            field=models.CharField(default='undefined', help_text='Nombre o alias para identificar esta credencial', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='clientmarketplacecredentials',
            unique_together={('client', 'marketplace_type', 'name')},
        ),
    ]
