# Generated by Django 5.2.4 on 2025-08-07 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('marketplace_type', models.CharField(choices=[('amazon', 'Amazon'), ('mercadolibre', 'Mercado Libre'), ('shopify', 'Shopify'), ('ebay', 'eBay'), ('walmart', 'Walmart')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sale_channels',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_type', models.CharField(choices=[('amazon', 'Amazon'), ('mercadolibre', 'Mercado Libre'), ('shopify', 'Shopify'), ('ebay', 'eBay'), ('walmart', 'Walmart')], max_length=50)),
                ('marketplace_id', models.CharField(max_length=100)),
                ('external_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('inventory_quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_fulfillment', models.BooleanField(default=False)),
                ('listing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('official_store_name', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('permalink', models.URLField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='clients.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='products.product')),
            ],
            options={
                'db_table': 'marketplace_listings',
                'unique_together': {('client', 'marketplace_type', 'marketplace_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_sales', models.IntegerField(blank=True, null=True)),
                ('utility_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('market_share', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='clients.client')),
                ('marketplace_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='marketplaces.marketplacelisting')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'db_table': 'product_price_history',
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductTracing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_type', models.CharField(choices=[('amazon', 'Amazon'), ('mercadolibre', 'Mercado Libre'), ('shopify', 'Shopify'), ('ebay', 'eBay'), ('walmart', 'Walmart')], max_length=50)),
                ('marketplace_id', models.CharField(max_length=100)),
                ('seller_name', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_id', models.CharField(blank=True, max_length=100, null=True)),
                ('power_seller_status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_checked_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tracing', to='clients.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracing', to='products.product')),
            ],
            options={
                'db_table': 'product_tracing',
                'unique_together': {('client', 'product', 'marketplace_type', 'marketplace_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductTracingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_count', models.IntegerField(blank=True, null=True)),
                ('inventory_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracing_history', to='clients.client')),
                ('product_tracing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='marketplaces.producttracing')),
            ],
            options={
                'db_table': 'product_tracing_history',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('match_type', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual'), ('rejected', 'Rechazado')], default='auto', max_length=50)),
                ('match_criteria', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('rejected', 'Rechazado')], default='active', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='clients.client')),
                ('marketplace_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='marketplaces.marketplacelisting')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_matches',
                'unique_together': {('client', 'product', 'marketplace_listing')},
            },
        ),
    ]
